In [34]:
sent = [
    "The glass of a milk",
    "It is a nice to meet You",
    "Hello my name is soham",
    "Milk is a good and healthy drink",
    "Game is a virtual thing "
]

In [35]:
from tensorflow.keras.preprocessing.text import one_hot

In [36]:
#define vocabulary size

voc = 10000

In [39]:
one_hot_rep = []
for word in sent:
    one_hot_rep.append(one_hot(word,voc))

print(one_hot_rep)
    

[[218, 2685, 3382, 3566, 1839], [9354, 3670, 3566, 8749, 5540, 9107, 6307], [3935, 500, 9154, 3670, 6782], [1839, 3670, 3566, 4859, 3528, 5851, 8005], [9132, 3670, 3566, 5994, 3431]]


In [40]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [41]:
import numpy as np

In [42]:
sent_length = 10
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0    0  218 2685 3382 3566 1839]
 [   0    0    0 9354 3670 3566 8749 5540 9107 6307]
 [   0    0    0    0    0 3935  500 9154 3670 6782]
 [   0    0    0 1839 3670 3566 4859 3528 5851 8005]
 [   0    0    0    0    0 9132 3670 3566 5994 3431]]


In [43]:
## feature represent

dim = 10

In [53]:
model = Sequential()
model.add(Embedding(voc,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\sarka\RNN_project\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [47]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [33]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[[ 0.03783363,  0.03045319,  0.00665536,  0.01107808,
          0.03960652, -0.04275988,  0.04370568,  0.04405436,
         -0.04404841,  0.02941949],
        [ 0.03783363,  0.03045319,  0.00665536,  0.01107808,
          0.03960652, -0.04275988,  0.04370568,  0.04405436,
         -0.04404841,  0.02941949],
        [ 0.03783363,  0.03045319,  0.00665536,  0.01107808,
          0.03960652, -0.04275988,  0.04370568,  0.04405436,
         -0.04404841,  0.02941949],
        [ 0.03783363,  0.03045319,  0.00665536,  0.01107808,
          0.03960652, -0.04275988,  0.04370568,  0.04405436,
         -0.04404841,  0.02941949],
        [ 0.03783363,  0.03045319,  0.00665536,  0.01107808,
          0.03960652, -0.04275988,  0.04370568,  0.04405436,
         -0.04404841,  0.02941949],
        [-0.00182765,  0.02917923, -0.02816533, -0.02869819,
          0.04998854, -0.03662684, -0.02400193,  0.00084579,
          0.00878371, -0.01417162],
        [-0.01416482, -0.02103262,  0.0026447 ,  0.0

In [56]:
model.fit(
    embedded_docs
)

ValueError: Attr 'Toutput_types' of 'OptionalFromValue' Op passed list of length 0 less than minimum 1.

In [51]:
embedded_docs

array([[   0,    0,    0,    0,    0,  218, 2685, 3382, 3566, 1839],
       [   0,    0,    0, 9354, 3670, 3566, 8749, 5540, 9107, 6307],
       [   0,    0,    0,    0,    0, 3935,  500, 9154, 3670, 6782],
       [   0,    0,    0, 1839, 3670, 3566, 4859, 3528, 5851, 8005],
       [   0,    0,    0,    0,    0, 9132, 3670, 3566, 5994, 3431]],
      dtype=int32)